(use-modules (guix packages)
             (guix licenses)
             (guix download)
             (guix git-download)
             (guix build-system gnu)
             (guix utils)

             (gnu packages)
             (gnu packages autotools)
             (gnu packages pkg-config)
             (gnu packages gettext)
             (gnu packages m4)
             (gnu packages guile)
             (gnu packages glib)
             (gnu packages gnome))

(package
 (name "guile-gobject-introspection")
 (version "0.1")
 (source #f)
 (build-system gnu-build-system)
 (native-inputs
  `(("pkg-config" ,pkg-config)
    ("glib" ,glib)
    ("guile" ,guile-2.2)
    ("libtool" ,libtool)
    ("gettext" ,gettext)
    ("autoconf" ,autoconf)
    ("automake" ,automake)))
 (inputs
  `(("guile" ,guile-2.2) ("gobject-introspection" ,gobject-introspection)))
 (native-search-paths (package-native-search-paths gobject-introspection))
 (synopsis "Guile bindings for GObject")
 (description "Guile bindings for GLib, GObject, and GIO.")
 (home-page "https://git.bonerbonerboner.com/")
 (license gpl3+))
